"use client";
import { useEffect, useState } from "react";
import { FileText, Send } from "lucide-react";

type Assignment = { id: string; title: string; student_id: string; student_name: string; file_name: string; created_at: string };
export function ClassAssignmentDelivery({ classId }: { classId: string }) {
  const [assignments, setAssignments] = useState<Assignment[]>([]); const [message, setMessage] = useState<string | null>(null); const [sending, setSending] = useState<string | null>(null);
  useEffect(() => { void fetch(`/api/classes/${classId}/assignments`).then(async r => { const p = await r.json() as { assignments?: Assignment[]; error?: string }; if (!r.ok) throw new Error(p.error); setAssignments(p.assignments ?? []); }).catch(e => setMessage(e.message)); }, [classId]);
  async function send(assignment: Assignment) { setSending(assignment.id); setMessage(null); try { const response = await fetch("/api/vivas", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ classId, assignmentId: assignment.id, studentId: assignment.student_id }) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error); setMessage(`Viva sent to ${assignment.student_name}. It is now in their To do list.`); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not send Viva."); } finally { setSending(null); } }
  return <main className="min-h-screen bg-white px-5 py-8 text-[#171717] sm:px-8"><div className="mx-auto max-w-4xl"><a className="text-sm font-semibold" href="/classes">← Classes</a><section className="mt-6 rounded-[2rem] bg-[#FBE994] p-7 sm:p-10"><p className="text-xs font-semibold tracking-[.14em] uppercase text-[#695915]">Teacher workspace</p><h1 className="mt-3 text-4xl font-bold tracking-[-.05em]">Choose work, then send a Viva.</h1><p className="mt-4 max-w-2xl leading-7 text-[#51491e]">Each card belongs to one enrolled student. Sending creates a private pending Viva only they can open.</p></section><section className="mt-8 space-y-4">{assignments.map(assignment => <article className="flex flex-wrap items-center justify-between gap-4 rounded-[1.25rem] border border-[#e7e3d8] p-5 shadow-[0_12px_28px_rgba(70,55,30,.05)]" key={assignment.id}><div className="flex gap-3"><FileText className="mt-1 size-5 text-[#856b12]"/><div><p className="font-semibold">{assignment.title}</p><p className="mt-1 text-sm text-[#655d52]">{assignment.student_name} · {assignment.file_name}</p></div></div><button className="inline-flex items-center gap-2 rounded-full bg-[#171717] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60" disabled={sending === assignment.id} onClick={() => void send(assignment)}>{sending === assignment.id ? "Sending…" : <>Send Viva <Send className="size-4"/></>}</button></article>)}{assignments.length === 0 ? <p className="rounded-[1.25rem] border border-dashed border-[#d8d3c8] p-10 text-center text-sm text-[#655d52]">No student submissions yet. Ask enrolled students to upload work from their Viva dashboard.</p> : null}</section>{message ? <p className="mt-5 text-sm text-[#655d52]">{message}</p> : null}</div></main>;
}
